version: '3.9'

services:
  app_capstone:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '8000:8000'
    networks:
      - capstone_net
    environment:
      PGSQL_HOST: postgres_capstone
      PGSQL_PORT: 5432
      PGSQL_USER: postgres
      PGSQL_PASSWORD: postgres
      PGSQL_DB_NAME: postgres_capstone
    depends_on:
      postgres_capstone:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    networks:
      - capstone_net
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - app_capstone
    stdin_open: true
    tty: true

  postgres_capstone:
    image: 'postgres:17'
    ports:
      - '5432:5432'
    networks:
      - capstone_net
    volumes:
      - postgres_data_capstone:/var/lib/postgresql:rw
    environment:
      POSTGRES_DB: postgres_capstone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/17/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  capstone_net:
    driver: bridge

volumes:
  postgres_data_capstone:
