"""updated_by_created_by_added_to_reminder.

Revision ID: 2d7a78c32a14
Revises: 0e3322cc2f37
Create Date: 2026-04-19 16:56:04.784106

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d7a78c32a14'
down_revision: str | Sequence[str] | None = '0e3322cc2f37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('reminders', sa.Column('completed_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reminders', 'users', ['completed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reminders', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'completed_by')
    op.drop_column('reminders', 'updated_by')
    # ### end Alembic commands ###
