"""replace_is_completed_with_status_enum.

Revision ID: 2e19dc1a0838
Revises: b3ad26fd8e05
Create Date: 2026-05-11 21:16:00.823849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e19dc1a0838'
down_revision: str | Sequence[str] | None = 'b3ad26fd8e05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE reminderstatus AS ENUM ('pending', 'in_progress', 'completed', 'overdue')")
    op.add_column(
        'reminders',
        sa.Column(
            'status',
            sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='reminderstatus'),
            server_default='pending',
            nullable=False,
        ),
    )
    op.drop_column('reminders', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    op.drop_column('reminders', 'status')
    op.execute('DROP TYPE reminderstatus')
    # ### end Alembic commands ###
