"""make_notification_reminder_id_nullable.

Revision ID: 921ec0e57e70
Revises: f2538cf1ad37
Create Date: 2026-05-21 15:51:55.619575

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '921ec0e57e70'
down_revision: str | Sequence[str] | None = 'f2538cf1ad37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_recipients', 'reminder_id', existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_recipients', 'reminder_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
