"""add_timezone_to_users.

Revision ID: b3ad26fd8e05
Revises: f82bb466a060
Create Date: 2026-05-09 12:21:22.763009

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3ad26fd8e05'
down_revision: str | Sequence[str] | None = 'f82bb466a060'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'timezone',
            sa.VARCHAR(length=50),
            server_default='UTC',
            nullable=False,
            comment='User timezone (e.g., UTC, America/New_York, Asia/Yerevan)',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
