"""Add reassignment requests table.

Revision ID: f2538cf1ad37
Revises: 2605713ce543
Create Date: 2026-05-21 14:49:18.812816

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f2538cf1ad37'
down_revision: str | Sequence[str] | None = '2605713ce543'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reassignment_requests',
        sa.Column('reminder_id', sa.UUID(), nullable=False),
        sa.Column('requester_id', sa.UUID(), nullable=False),
        sa.Column('current_assignee_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['current_assignee_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_reassignment_requests_current_assignee_id'),
        'reassignment_requests',
        ['current_assignee_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_reassignment_requests_reminder_id'), 'reassignment_requests', ['reminder_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reassignment_requests_reminder_id'), table_name='reassignment_requests')
    op.drop_index(op.f('ix_reassignment_requests_current_assignee_id'), table_name='reassignment_requests')
    op.drop_table('reassignment_requests')
    # ### end Alembic commands ###
